# Generated by Django 5.0.7 on 2024-07-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCharact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Мужик'), ('F', 'Псевдомужик')], max_length=100, null=True, verbose_name='Пол')),
                ('age', models.IntegerField(null=True, verbose_name='Возраст')),
                ('profession', models.CharField(max_length=250, null=True, verbose_name='Профессия')),
                ('health', models.CharField(max_length=250, null=True, verbose_name='Здоровье')),
                ('hobbii', models.CharField(max_length=250, null=True, verbose_name='Хобби')),
                ('phobia', models.CharField(max_length=250, null=True, verbose_name='Фобия')),
                ('baggage', models.CharField(max_length=250, null=True, verbose_name='Багаж')),
                ('fact_1', models.CharField(max_length=250, null=True, verbose_name='Факт-1')),
                ('fact_2', models.CharField(max_length=250, null=True, verbose_name='Факт-2')),
            ],
            options={
                'verbose_name': 'Информация об игроках',
                'verbose_name_plural': 'Информация об игроках',
            },
        ),
    ]
