# Generated by Django 5.0 on 2024-09-18 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information1',
        ),
    ]
