# Generated by Django 5.1 on 2024-08-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_app', '0002_alter_membercharact_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercharact',
            name='baggage',
            field=models.CharField(choices=[('One backpack', 'Один рюкзак'), ('Two suitcases', 'Два чемодана'), ('Bag and suitcase', 'Сумка и чемодан'), ('Hand luggage only', 'Только ручная кладь')], max_length=250, null=True, verbose_name='Багаж'),
        ),
        migrations.AlterField(
            model_name='membercharact',
            name='health',
            field=models.CharField(choices=[('Perfect', 'Отличное'), ('Good', 'Хорошее'), ('Normal', 'Среднее'), ('Bad', 'Плохое')], max_length=250, null=True, verbose_name='Здоровье'),
        ),
        migrations.AlterField(
            model_name='membercharact',
            name='hobbii',
            field=models.CharField(choices=[('Reading', 'Чтение'), ('Sport', 'Спорт'), ('Traveling', 'Путешествия'), ('Music', 'Музыка'), ('Movie', 'Кино')], max_length=250, null=True, verbose_name='Хобби'),
        ),
        migrations.AlterField(
            model_name='membercharact',
            name='phobia',
            field=models.CharField(choices=[('Height', 'Высоты'), ('Confined space', 'Замкнутое пространство'), ('Spiders', 'Пауки'), ('Mouses', 'Мыши'), ('Darkness', 'Темнота')], max_length=250, null=True, verbose_name='Фобия'),
        ),
        migrations.AlterField(
            model_name='membercharact',
            name='sex',
            field=models.CharField(choices=[('Men', 'Мужик'), ('Woomen', 'Псевдомужик')], max_length=100, null=True, verbose_name='Пол'),
        ),
    ]
