# Generated by Django 5.1 on 2024-08-09 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_app', '0003_alter_membercharact_baggage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercharact',
            name='stage',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100, message='Значение должно быть меньше или равно 100')], verbose_name='Стадия'),
        ),
    ]
