# Generated by Django 5.0 on 2024-09-18 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_app', '0003_information1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Information1',
            new_name='Information',
        ),
    ]
