# Generated by Django 5.1 on 2024-08-09 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_app', '0004_membercharact_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercharact',
            name='age',
            field=models.PositiveIntegerField(null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='membercharact',
            name='stage',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100, message='Значение должно быть меньше или равно 100')], verbose_name='Стадия'),
        ),
    ]
