# Generated by Django 5.1 on 2024-08-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_app', '0005_alter_membercharact_age_alter_membercharact_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membercharact',
            name='stage',
        ),
    ]
