# Generated by Django 5.1 on 2024-08-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_app', '0007_membercharact_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baggage', models.CharField(max_length=100, null=True)),
                ('baggage_rus', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.CharField(max_length=100, null=True)),
                ('health_rus', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hobbii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbii', models.CharField(max_length=100, null=True)),
                ('hobbii_rus', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phobia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phobie', models.CharField(max_length=100, null=True)),
                ('phobie_rus', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=100, null=True)),
                ('profession_rus', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='membercharact',
            name='sex',
            field=models.CharField(choices=[('Men', 'Мужик'), ('Woomen', 'Псевдомужик'), ('Men barren', 'Мужчина бесплодный'), ('Woomen barren', 'Женщина бесплодная')], max_length=100, null=True, verbose_name='Пол'),
        ),
    ]
