# Generated by Django 5.1 on 2024-08-09 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_app', '0008_baggage_health_hobbii_phobia_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercharact',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bunker_app.profession'),
        ),
        migrations.AlterField(
            model_name='membercharact',
            name='sex',
            field=models.CharField(choices=[('Men', 'Мужик'), ('Woomen', 'Женщина'), ('Men barren', 'Мужчина бесплодный'), ('Woomen barren', 'Женщина бесплодная')], max_length=100, null=True, verbose_name='Пол'),
        ),
    ]
