# Generated by Django 5.1 on 2024-08-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_app', '0009_alter_membercharact_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercharact',
            name='profession',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
