# Generated by Django 5.1 on 2024-08-12 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_app', '0010_alter_membercharact_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercharact',
            name='profession',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof', to='bunker_app.profession'),
        ),
    ]
