# Generated by Django 5.1 on 2024-08-12 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_app', '0011_alter_membercharact_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baggage',
            old_name='baggage',
            new_name='baggage_en',
        ),
        migrations.RenameField(
            model_name='baggage',
            old_name='baggage_rus',
            new_name='baggage_ru',
        ),
        migrations.RenameField(
            model_name='health',
            old_name='health',
            new_name='health_en',
        ),
        migrations.RenameField(
            model_name='health',
            old_name='health_rus',
            new_name='health_ru',
        ),
        migrations.RenameField(
            model_name='hobbii',
            old_name='hobbii',
            new_name='hobbii_en',
        ),
        migrations.RenameField(
            model_name='hobbii',
            old_name='hobbii_rus',
            new_name='hobbii_ru',
        ),
        migrations.RenameField(
            model_name='phobia',
            old_name='phobie',
            new_name='phobie_en',
        ),
        migrations.RenameField(
            model_name='phobia',
            old_name='phobie_rus',
            new_name='phobie_ru',
        ),
        migrations.RenameField(
            model_name='profession',
            old_name='profession',
            new_name='profession_en',
        ),
        migrations.RenameField(
            model_name='profession',
            old_name='profession_rus',
            new_name='profession_ru',
        ),
        migrations.AlterField(
            model_name='membercharact',
            name='baggage',
            field=models.ForeignKey(max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baggage', to='bunker_app.baggage', verbose_name='Багаж'),
        ),
        migrations.AlterField(
            model_name='membercharact',
            name='health',
            field=models.ForeignKey(max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health', to='bunker_app.health', verbose_name='Здоровье'),
        ),
        migrations.AlterField(
            model_name='membercharact',
            name='hobbii',
            field=models.ForeignKey(max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hobbii', to='bunker_app.hobbii', verbose_name='Хобби'),
        ),
        migrations.AlterField(
            model_name='membercharact',
            name='phobia',
            field=models.ForeignKey(max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phobia', to='bunker_app.phobia', verbose_name='Фобия'),
        ),
        migrations.AlterField(
            model_name='membercharact',
            name='profession',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profession', to='bunker_app.profession', verbose_name='Профессия'),
        ),
    ]
