# Generated by Django 5.1 on 2024-08-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_app', '0013_remove_membercharact_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercharact',
            name='profession',
            field=models.ManyToManyField(max_length=100, related_name='profession', to='bunker_app.profession', verbose_name='Профессия'),
        ),
    ]
