# Generated by Django 5.1 on 2024-08-12 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_app', '0014_alter_membercharact_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membercharact',
            name='health',
        ),
        migrations.RemoveField(
            model_name='membercharact',
            name='profession',
        ),
        migrations.AddField(
            model_name='membercharact',
            name='health',
            field=models.ManyToManyField(max_length=250, related_name='health', to='bunker_app.health', verbose_name='Здоровье'),
        ),
        migrations.AddField(
            model_name='membercharact',
            name='profession',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profession', to='bunker_app.profession', verbose_name='Профессия'),
        ),
    ]
