# Generated by Django 5.1 on 2024-08-12 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_app', '0015_remove_membercharact_health_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membercharact',
            name='health',
        ),
        migrations.AddField(
            model_name='membercharact',
            name='health',
            field=models.ForeignKey(max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health', to='bunker_app.health', verbose_name='Здоровье'),
        ),
    ]
