# Generated by Django 5.1 on 2024-08-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_app', '0016_remove_membercharact_health_membercharact_health'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membercharact',
            name='health',
        ),
        migrations.AddField(
            model_name='membercharact',
            name='health',
            field=models.ManyToManyField(max_length=250, related_name='health', to='bunker_app.health', verbose_name='Здоровье'),
        ),
    ]
