# Generated by Django 5.1 on 2024-08-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_app', '0018_remove_membercharact_health_membercharact_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercharact',
            name='infection',
            field=models.CharField(max_length=250, null=True, verbose_name='Заражения'),
        ),
    ]
