# Generated by Django 5.1 on 2024-08-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_app', '0020_membercharact_alive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phobia',
            old_name='phobie_en',
            new_name='phobia_en',
        ),
        migrations.RenameField(
            model_name='phobia',
            old_name='phobie_ru',
            new_name='phobia_ru',
        ),
    ]
