# Generated by Django 5.1 on 2024-08-14 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_app', '0021_rename_phobie_en_phobia_phobia_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_en', models.CharField(max_length=250, null=True)),
                ('fact_ru', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='membercharact',
            name='fact_1',
            field=models.ForeignKey(max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fact_1', to='bunker_app.fact', verbose_name='Факт-1'),
        ),
        migrations.AlterField(
            model_name='membercharact',
            name='fact_2',
            field=models.ForeignKey(max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fact_2', to='bunker_app.fact', verbose_name='Факт-2'),
        ),
    ]
