# Generated by Django 5.1 on 2024-08-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_app', '0023_alter_membercharact_alive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercharact',
            name='alive',
            field=models.BooleanField(default=True, verbose_name='Живой'),
        ),
    ]
