# Generated by Django 5.1 on 2024-08-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_app', '0024_alter_membercharact_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercharact',
            name='breeding_points',
            field=models.IntegerField(default=0, verbose_name='Очки размножения'),
        ),
        migrations.AddField(
            model_name='membercharact',
            name='survive_points',
            field=models.IntegerField(default=0, verbose_name='Очки выживания'),
        ),
    ]
