# Generated by Django 5.1 on 2024-08-15 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_app', '0025_membercharact_breeding_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membercharact',
            old_name='survive_points',
            new_name='survival_points',
        ),
    ]
