# Generated by Django 5.0.7 on 2024-07-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0011_alter_women_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
