# Generated by Django 4.2.1 on 2024-06-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='telegram',
            field=models.URLField(blank=True),
        ),
    ]
