# Generated by Django 4.2.1 on 2024-06-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0003_members_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
