# Generated by Django 4.2.1 on 2024-06-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0004_members_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=255)),
                ('rules', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='members',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
