# Generated by Django 4.2.1 on 2024-06-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0005_games_alter_members_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
