# Generated by Django 5.0.7 on 2024-07-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0007_members_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='points',
            field=models.IntegerField(),
        ),
    ]
