# Generated by Django 5.0.7 on 2024-07-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0009_alter_members_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='members',
            name='content',
            field=models.TextField(blank=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='members',
            name='discord',
            field=models.URLField(unique=True, verbose_name='Дискорд'),
        ),
        migrations.AlterField(
            model_name='members',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='members',
            name='points',
            field=models.IntegerField(verbose_name='Очки'),
        ),
        migrations.AlterField(
            model_name='members',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='members',
            name='telegram',
            field=models.URLField(blank=True, verbose_name='Тг'),
        ),
    ]
