# Generated by Django 5.0.7 on 2024-07-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0010_members_photo_alter_members_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='loses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='wins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
