# Generated by Django 5.0.7 on 2024-07-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0011_members_loses_members_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='loses',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='members',
            name='wins',
            field=models.IntegerField(),
        ),
    ]
