# Generated by Django 5.0.7 on 2024-07-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0012_alter_members_loses_alter_members_wins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='content',
        ),
        migrations.RemoveField(
            model_name='games',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='games',
            name='slug',
        ),
        migrations.AddField(
            model_name='games',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='games',
            name='url',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название игры'),
        ),
        migrations.AlterField(
            model_name='members',
            name='loses',
            field=models.IntegerField(verbose_name='Поражения'),
        ),
        migrations.AlterField(
            model_name='members',
            name='wins',
            field=models.IntegerField(verbose_name='Победы'),
        ),
    ]
